# Generated by Django 4.2.7 on 2025-05-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cruise_speed", models.FloatField()),
                ("max_altitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("focal_length", models.FloatField()),
                ("sensor_width", models.FloatField()),
                ("sensor_height", models.FloatField()),
                ("pixel_size", models.FloatField()),
            ],
        ),
    ]
