# Generated by Django 4.2.7 on 2025-05-26 12:00

from django.db import migrations, models


def update_aircraft_speeds(apps, schema_editor):
    Aircraft = apps.get_model('planner_nalotu', 'Aircraft')
    for aircraft in Aircraft.objects.all():
        # Calculate min_speed and max_speed based on cruise_speed
        # We'll use a 20% range around the cruise_speed
        min_speed = aircraft.cruise_speed * 0.8
        max_speed = aircraft.cruise_speed * 1.2
        
        aircraft.min_speed = min_speed
        aircraft.max_speed = max_speed
        aircraft.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planner_nalotu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='min_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(update_aircraft_speeds),
        migrations.RemoveField(
            model_name='aircraft',
            name='cruise_speed',
        ),
    ]